version: '3.8'

services:
  sql_server_ticketmanager:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server_container_ticketmanager
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "TicketManager!1"
      MSSQL_PID: Express
    ports:
      - "1433:1433"